spring:
  data:
    mongodb:
      uri:mongodb+srv://zainabilma244901:sc2KwvC0NYPdWZ5S@cluster0.8rapy.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database:journaldb
      auto-index-creation:true
 
server:
  port:
    servlet:
      context-path: