server:
  port: 8080
  servlet:
    context-path: /

spring:
  data:
    mongodb:
      uri: mongodb+srv://zainabilma244901:sc2KwvC0NYPdWZ5S@cluster0.8rapy.mongodb.net/journaldb?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      auto-index-creation: true
    redis:
      url: redis://default:KOE82zJ1GrLOpu3JH0Stz0KnCA33ulW7@redis-13668.c305.ap-south-1-1.ec2.cloud.redislabs.com:13668
#      host: localhost     #when we use redis on local machine
#      port: 6379 #port for redis service

  mail:
    host: smtp.gmail.com
    port: 587 #since we are using encryption otherwise default port is 25
    username: zainabilma244901@gmail.com
    password: htdokpurkclrnvtp  # I removed spaces â€” passwords must be a single string
    properties:
      mail:
        smtp:
          auth: true
          starttls: #stands for statrTransportLayerSecurity, used for encryption while data transfer btw app and mail
            enable: true
  kafka:
    bootstrap-servers: pkc-9q8rv.ap-south-2.aws.confluent.cloud:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: weekly-sentiments-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.zainab.journalApp.model
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: PLAIN
        jaas:
          config: >
            org.apache.kafka.common.security.plain.PlainLoginModule required
            username='H2OO5MNXZI6URFZT'
            password='cflt9bOsLTekpAa7lhAxTssMjxWjxyRVIp1vDzyZJ50IUCtSspxloLd3Wvrww8CQ';
      session:
        timeout:
          ms: 45000
      client:
        id: ccloud-springboot-client-4c5664da-065f-4e8f-a585-09f529bbfb49
quotes:
  api:
    key: JE2aOkm6HGVar+qIVw3J+A==doRRyvtfGS7NMTWF

weather_api_key: JE2aOkm6HGVar+qIVw3J+A==doRRyvtfGS7NMTWF

